version: '3.8'

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "5001:5001"
      - "8083:8080"
    volumes:
      - ./ipfs_data:/data/ipfs
    restart: unless-stopped

  graph-node-base:
    image: graphprotocol/graph-node:latest
    environment:
      - postgres_host=10.200.21.15
      - postgres_port=7432
      - postgres_user=blockscout
      - postgres_pass=ceWb1MeLBEeOIfk65gU8EjF8
      - postgres_db=blockscout
      - ipfs=ipfs:5001
      - ethereum=http://10.200.21.53:8655
      - ethereum=cysic-dev:http://10.200.21.53:8655  # 自定义 RPC 节点
      - RUST_LOG=info
    depends_on:
      - ipfs
    restart: unless-stopped

  graph-node-blocks:
    extends:
      service: graph-node-base
    ports:
      - "8020:8020"

  graph-node-exchange-cake-pairs:
    extends:
      service: graph-node-base
    ports:
      - "8120:8020"

  graph-node-exchange-v2:
    extends:
      service: graph-node-base
    ports:
      - "8220:8020"

  graph-node-exchange-v3:
    extends:
      service: graph-node-base
    ports:
      - "8320:8020"

  graph-node-pairs:
    extends:
      service: graph-node-base
    ports:
      - "8420:8020"

  graph-node-user-position-v3:
    extends:
      service: graph-node-base
    ports:
      - "8520:8020"




  graph-deploy-blocks:
    image: graphprotocol/graph-node:latest
    depends_on:
      - graph-node-blocks
      - ipfs
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["graph", "deploy", "--node", "http://graph-node-blocks:8020", "--ipfs", "http://ipfs:5001", "cysicswap/blocks", "subgraph.yaml"]

  graph-deploy-exchange-cake-pairs:
    image: graphprotocol/graph-node:latest
    depends_on:
      - graph-node-exchange-cake-pairs
      - ipfs
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["graph", "deploy", "--node", "http://graph-node-exchange-cake-pairs:8020", "--ipfs", "http://ipfs:5001", "cysicswap/exchange-cake-pairs", "subgraph.yaml"]

  graph-deploy-exchange-v2:
    image: graphprotocol/graph-node:latest
    depends_on:
      - graph-node-exchange-v2
      - ipfs
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["graph", "deploy", "--node", "http://graph-node-exchange-v2:8020", "--ipfs", "http://ipfs:5001", "cysicswap/exchange-v2", "subgraph.yaml"]

  graph-deploy-exchange-v3:
    image: graphprotocol/graph-node:latest
    depends_on:
      - graph-node-exchange-v3
      - ipfs
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["graph", "deploy", "--node", "http://graph-node-exchange-v3:8020", "--ipfs", "http://ipfs:5001", "cysicswap/exchange-v3", "subgraph.yaml"]

  graph-deploy-pairs:
    image: graphprotocol/graph-node:latest
    depends_on:
      - graph-node-pairs
      - ipfs
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["graph", "deploy", "--node", "http://graph-node-pairs:8020", "--ipfs", "http://ipfs:5001", "cysicswap/pairs", "subgraph.yaml"]

  graph-deploy-user-position-v3:
    image: graphprotocol/graph-node:latest
    depends_on:
      - graph-node-user-position-v3
      - ipfs
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["graph", "deploy", "--node", "http://graph-node-user-position-v3:8020", "--ipfs", "http://ipfs:5001", "cysicswap/user-position-v3", "subgraph.yaml"]


  graph-node-nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - graph-node-blocks
      - graph-node-exchange-cake-pairs
      - graph-node-exchange-v2
      - graph-node-exchange-v3
      - graph-node-pairs
      - graph-node-user-position-v3
    restart: unless-stopped