version: '3.8'


# Graph Node 基础配置
x-graph-node-base: &graph-node-base
  image: graphprotocol/graph-node:latest
  environment:
    - postgres_host=10.200.21.15
    - postgres_port=7432
    - postgres_user=blockscout
    - postgres_pass=ceWb1MeLBEeOIfk65gU8EjF8
    - postgres_db=blockscout
    - ipfs=ipfs:5001
    - ethereum=http://10.200.21.53:8655
    - ethereum=cysic-dev:http://10.200.21.53:8655  # 自定义 RPC 节点
    - RUST_LOG=info
    - GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH=true
    - GRAPH_LOG=debug
  depends_on:
    - ipfs
  restart: unless-stopped
  volumes: 
    - ./:/subgraph


services:
  # IPFS 服务
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "5001:5001"  # IPFS API 端口
      - "8083:8080"  # IPFS 网关端口
    volumes:
      - ./ipfs_data:/data/ipfs
    restart: unless-stopped

  # Graph Node 实例 1: blocks
  graph-node-blocks:
    <<: *graph-node-base
    ports:
      - "8000:8000"  # HTTP 端口（查询和 UI）
      - "8001:8001"  # WebSocket 端口（订阅）
      - "8020:8020"  # Indexer 管理端口
      - "8030:8030"
      - "8040:8040"

  # Graph Node 实例 2: exchange-cake-pairs
  # graph-node-exchange-cake-pairs:
  #   <<: *graph-node-base
  #   ports:
  #     - "8100:8000"  # HTTP 端口
  #     - "8101:8001"  # WebSocket 端口
  #     - "8120:8020"  # Indexer 管理端口
  #     - "8130:8030"
  #     - "8140:8040"

  # Graph Node 实例 3: exchange-v2
  graph-node-exchange-v2:
    <<: *graph-node-base
    ports:
      - "8200:8000"  # HTTP 端口
      - "8201:8001"  # WebSocket 端口
      - "8220:8020"  # Indexer 管理端口
      - "8230:8030"
      - "8240:8040"

  # Graph Node 实例 4: exchange-v3
  graph-node-exchange-v3:
    <<: *graph-node-base
    # environment:
      # - postgres_db=exchange_v3_db  # 使用不同的数据库
    ports:
      - "8300:8000"  # HTTP 端口
      - "8301:8001"  # WebSocket 端口
      - "8320:8020"  # Indexer 管理端口
      - "8330:8030"
      - "8340:8040"

  # Graph Node 实例 5: pairs
  graph-node-pairs:
    <<: *graph-node-base
    ports:
      - "8400:8000"  # HTTP 端口
      - "8401:8001"  # WebSocket 端口
      - "8420:8020"  # Indexer 管理端口
      - "8430:8030"
      - "8440:8040"

  # Graph Node 实例 6: user-position-v3
  graph-node-user-position-v3:
    <<: *graph-node-base
    ports:
      - "8500:8000"  # HTTP 端口
      - "8501:8001"  # WebSocket 端口
      - "8520:8020"  # Indexer 管理端口
      - "8530:8030"
      - "8540:8040"

  # Nginx 反向代理
  graph-node-nginx:
    image: nginx:latest
    ports:
      - "8082:80"  # Nginx HTTP 端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - graph-node-blocks
      # - graph-node-exchange-cake-pairs
      - graph-node-exchange-v2
      - graph-node-exchange-v3
      - graph-node-pairs
      - graph-node-user-position-v3
    restart: unless-stopped


  # Graph CLI 服务（用于执行 graph deploy）
  graph-cli:
    image: node:latest  # 使用 Node.js 镜像
    volumes:
      - ./:/subgraphs  # 挂载 Subgraph 项目目录
    working_dir: /subgraphs
    entrypoint: "tail -f /etc/hosts"
    # entrypoint: >
    #   /bin/sh -c "
    #     # 安装 graph-cli
    #     npm install -f;

    #     # 等待 Graph Node 和 IPFS 服务启动
    #     sleep 10;

    #     npm run create
    #     npm run deploy
    #   "
    depends_on:
      - graph-node-blocks
      - graph-node-exchange-v2
      - graph-node-exchange-v3
      - graph-node-pairs
      - graph-node-user-position-v3
      - ipfs
    restart: on-failure