http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    upstream graph-node-blocks {
        server graph-node-blocks:8020;
    }

    upstream graph-node-exchange-cake-pairs {
        server graph-node-exchange-cake-pairs:8020;
    }

    upstream graph-node-exchange-v2 {
        server graph-node-exchange-v2:8020;
    }

    upstream graph-node-exchange-v3 {
        server graph-node-exchange-v3:8020;
    }

    upstream graph-node-pairs {
        server graph-node-pairs:8020;
    }

    upstream graph-node-user-position-v3 {
        server graph-node-user-position-v3:8020;
    }

    server {
        listen 80;

        location /subgraphs/name/cysicswap/ {
            # 提取子图名称
            rewrite ^/subgraphs/name/cysicswap/([^/]+) /$1 break;

            # 转发请求到对应的 graph-node 实例
            proxy_pass http://graph-node-$1;

            # 设置请求头
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Content-Type "application/json";
        }
    }
}